### ISSUE TITLE
DB Deployment 

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#110]
We deployed the application to AWS with an in-memory DB, but Postgres DB also should be deployed...

**Comment by vedatakses** [comment]
Could you share AWS credentials from any secure channel @taneresme?

**Comment by vedatakses** [comment]
Status Update:
- PostgreSQL is created on AWS, after the application redeployment, the required configuration will be done.

**Comment by vedatakses** [comment]
Closing this issue, the application deployed to RDS PostgreSQL.
