### ISSUE TITLE
Getting Memory by memoryId

### ISSUE THREAD

**Issue by vedatakses** [swe-ms-boun/2018fall-swe574-g1#112]
1) Endpoint to get memory by memoryId is required
- If memory type is PUBLIC, then everyone can retrieve it
- If memory type is PRIVATE, then only the owner of memory can see it
- If memory type is SOCIAL, then only the owner and follower of this user can see it

2) Fixing the following issue:
- Memory type will be PRIVATE on memory creation since it will require PATCH update, due to some reasons when the user doesn't continue updating memory after setting the title, this memory shouldn't be returned in PUBLIC memories list

**Comment by tugcanolgun** [comment]
Public retrieval is done.
The issue 2. Fixing the public, private memory is done.
#117

**Comment by vedatakses** [comment]
Closing this issue
