### ISSUE TITLE
Modifications for permission of master branch

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#15]
* committing permission for master branch will be canceled.

**Comment by taneresme** [comment]
@vedatakses, @tugcanolgun, @macukadam, @alidursen ;
Bros, I think that it would be better if we do not commit the code directly to ``master`` branch. Because that can cause us to override the some of the codes that are committed by someone else...

I have created this issue but after checking the protection rules, I saw that there is a protection rule for ``master`` branch already of requiring the approval of at least 2 reviewers.

My advice, making each commit to ``master`` through ``pull requests``.

If you have any different idea, we can discuss as well.

**Comment by taneresme** [comment]
@vedatakses @tugcanolgun @macukadam @alidursen,
If you do not have any comment about the topic below, I will be closing the issue?

**Comment by alidursen** [comment]
we're not committing to master branch anyway? it looks fine to me

**Comment by vedat-akses** [comment]
Looks fine to me!

**Comment by alidursen** [comment]
urging @taneresme to close the issue.
