### ISSUE TITLE
Class diagrams

### ISSUE THREAD

**Issue by tugcanolgun** [swe-ms-boun/2018fall-swe574-g1#25]
Please check and give your thoughts on this
https://goo.gl/Bh7NkL

**Comment by taneresme** [comment]
Thanks, Tugcan, let's discuss it in the meeting, I have also created a wiki page to store all these designs named 7.1. Database Design. After finalizing the design, we can put them into that document.

**Comment by tugcanolgun** [comment]
Class diagram is added to Wiki
