### ISSUE TITLE
Create Requirements

### ISSUE THREAD

**Issue by alidursen** [swe-ms-boun/2018fall-swe574-g1#3]
Step 1

**Comment by taneresme** [comment]
Requirements elicitation
* Determine requirements in an accordance to that we get through in the meeting.
* Populate all of them in wiki.

**Comment by taneresme** [comment]
Bro, could you please look at this document for a non-functional requirements as a sample : https://github.com/taneresme/swe.573.project/blob/master/docs.project/wolower.requirement-specification.pdf

**Comment by taneresme** [comment]
@vedatakses Hopefully, it will give you idea about that :)

**Comment by vedatakses** [comment]
Thanks, @taneresme. Non-functional requirements are also added. Closing the task.
