### ISSUE TITLE
Inquiring public memories

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#40]
* Implementation of querying public memories registered in the system. Associated requirements : 
  * [x] The system should allow the users to view the public memories.
  * ~~[ ] The system should allow the users to search for memories among public memories according to location, date range by using a text box and/or a Google Map frame.~~

**Comment by taneresme** [comment]
@vedatakses did you work on this issue?

**Comment by vedatakses** [comment]
@taneresme 
- only the second issue is left

**Comment by taneresme** [comment]
The second task in the issue canceled.
If we need later on, we will create another issue for it...
