### ISSUE TITLE
Sharing a new memory with pics (as private/public/social)

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#42]
* Functionalities to share new memories. Associated requirements:
  * [x] Registered users should be able to share their memories with location, date, picture and its story. Location and date should be mandatory fields.
  * [x] The system should allow the registered users to upload images for each memory when sharing them.
  * [x] The system should allow registered users to share their memories privately (private memory).
  * [x] The registered users should be able to share their memories in three different ways. These are public memories, private memories, and social memories.

**Comment by taneresme** [comment]
@tugcanolgun and @vedatakses you are working on this issue and also we implemented some of them. I am assigning this issue to you.

**Comment by vedatakses** [comment]
- From backend point of view, they are supported at the moment.
- @tugcanolgun let's discuss once you continue since we need a refactor on APIs.

**Comment by tugcanolgun** [comment]
Done with #136
