### ISSUE TITLE
Inquiring all details of a memory

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#46]
Implementation of inquiring the details of a specific memory. Associated requirements:
  * [x] The Google Map widget should allow the users (regardless of registration) to go to the details of the memories by clicking on the thumbnails.
  * ~~[ ] The system should allow the registered users to go to the memories by using their annotations.~~
  * [x] The system should allow the registered users to like the memories shared by the users whom they follow.
  * [x] Registered users should be able to see how many like they have for each of their memories.
  * [x] Registered users should be able to see who liked each of their memories.

**Comment by tugcanolgun** [comment]
Partially done #117

**Comment by taneresme** [comment]
@tugcanolgun bro, can you mark the completed items below, it will be easier to track where we are.

**Comment by taneresme** [comment]
The second task in the issue canceled. If we need it again, we will create another issue.
