### ISSUE TITLE
Determining and documenting of development environment

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#6]
* Git repo branching organization will be organized
* CI/CD tools will be integrating with the repo
* Code quality tools will be integrating with the repo
* Development manifesto such as what kind of approaches will be used during the development will be created and documented in wiki pages...

**Comment by tugcanolgun** [comment]
Git branching is now open for discussion in https://github.com/swe-ms-boun/2018fall-swe574-g1/issues/8

**Comment by tugcanolgun** [comment]
For travis integration organizational access is required. So we are waiting the approval.

![image](https://user-images.githubusercontent.com/18149492/46248976-f0f39a80-c429-11e8-8380-0766c2ee6d11.png)

**Comment by tugcanolgun** [comment]
codacy.com code quality tool integration request is sent. We are waiting for the approval.

**Comment by alidursen** [comment]
> codacy.com code quality tool integration request is sent. We are waiting for the approval.

Any updates on this?

I believe we had determined the tools, but maybe not documented them.

**Comment by tugcanolgun** [comment]
This issue is now resolved. Im closing it.
