### ISSUE TITLE
Index page

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#61]
* Development of index page which is a public page that can be used by any user. Associated requirements:
  * [x] The system should allow the users to view the public memories.
  * ~~[ ] The system should allow the users to search for memories among public memories according to location, date range by using a text box and/or a Google Map frame.~~
  * [x] The users should be able to view the amenities of the system such as the total number of registered users, the total number of shared memories in the system, the total number of the shared pictures.

**Comment by tugcanolgun** [comment]
A static index page (based on the mock ups) is complete #97

**Comment by macukadam** [comment]
only the second issue is left

**Comment by taneresme** [comment]
The second task in the issues canceled.
If we need this functionality later, we will create another issue.
