### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#65]
* User profile page. Associated requirements:
  * [x] Registered users should be able to save and update their personal pieces of information such as birthdate, gender, the city and country they live.
  * [x] Registered users should be able to change their password after providing their email address and current password.
  * [x] Registered users should be able to view the information they provided during registration on their profile.
  * [x] The system should allow registered users to view the other registered users' profiles.
  * [x] The system should display all memories shared by registered users in their profile in a reverse-chronological order.
  * [x] The system should allow the registered users to view the other registered users' public memories on their profile.
  * [x] Index page, homepage and profile page of the registered users should display the memories ~~on a Google Map widget.~~

**Comment by tugcanolgun** [comment]
I guess you should take over this issue now @taneresme

**Comment by taneresme** [comment]
Closed in the PR #137
