### ISSUE TITLE
Page of sharing new memory 

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#66]
Development of sharing new memory page. Associated requirements:
  * [x] Registered users should be able to share their memories with location, date, picture and its story. Location and date should be mandatory fields.
  * [x] The system should allow the registered users to upload images for each memory when sharing them.
  * [x] The system should allow registered users to share their memories privately (private memory).
  * [x] The registered users should be able to share their memories in three different ways. These are public memories, private memories, and social memories.
  * [x] Registered users should be able to change the type of their memories after sharing them (i.e. from private to social, social to the public or public to private).

**Comment by tugcanolgun** [comment]
First step is complete with #86

**Comment by tugcanolgun** [comment]
Second step is complete with #97

**Comment by tugcanolgun** [comment]
What is currently lacking after #117 
* Locations are not saved
* Editor is vastly reduced. Can be configured after implementing postgresql connection
* Dropdown to select if it is public, social or private

**Comment by alidursen** [comment]
issue transformed into checkbox-list, first two checked per Tuğcan's report.

**Comment by tugcanolgun** [comment]
Done. #136
