### ISSUE TITLE
Developing map component with Google map

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#67]
* Will be developing a component hosted a map widget such as Google Map. Associated requirements:
  * Index page, homepage and profile page of the registered users should display the memories on a Google Map widget.
  * The system should allow the users (regardless of registration) to filter the pinned memories on the Google Map widget according to location and date range.
  * The users (regardless of registration) should be able to view a thumbnail of the memories by clicking on a pin on Google Map widget.
  * The Google Map widget should allow the users (regardless of registration) to go to the details of the memories by clicking on the thumbnails.
  * The system should allow the users to search for memories among public memories according to location, date range by using a text box and/or a Google Map frame.

**Comment by tugcanolgun** [comment]
First step is done with #97

**Comment by tugcanolgun** [comment]
What is lacking:
* Show real locations on index page instead of mockup random points.
* Show locations on memory-view page. Partially done, should not be hard to implement.
