### ISSUE TITLE
Implementation of memory annotation functionalities

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#68]
* Implementation of memory annotation functionalities. Associated requirements:
  * [x] Annotations shall be created, stored and shared according to W3C Web Annotation Data Model.
  * [x] Registered users should be able to annotate all public and social memories by image, text, location, and date with a text and tags.
  * [x] Registered users should be able to annotate one single memory maximum 5 times.

**Comment by tugcanolgun** [comment]
Partially completed as there is no running server currently. #117

**Comment by tugcanolgun** [comment]
Pattially complete with #136

@taneresme 
* Locations cannot be annotated.
* We can remove the maximum 5 times limit.

**Comment by tugcanolgun** [comment]
#143
