### ISSUE TITLE
Plan review and discussion 

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#70]
Hi All, 

I have created the planned issues on GitHub. Please review as much as issues you can and share your feedbacks under this issue. In this way, we can discuss your concerns and answer other questions.

**Comment by taneresme** [comment]
The determined reviewing process is as follows, please provide your feedback if any:
  * After completing a task, doer will be assigning the issue to the reviewer(s) with a label of ``review.pending``. 
  * After reviewing completed, the reviewer will assign the task to the doer back (if they have something to be done) with a label of ``review.needs-work``.
  * If there is nothing to be reviewed for the issue, the reviewer will tag it as ``review.done`` and close the issue.

**Comment by alidursen** [comment]
we can add one more step:
Projects automation allows reopened issues to be placed in a column. We can let it be "review" and therefore "after completing a task" does will close and reopen the issue with reviewers assigned?
