### ISSUE TITLE
Spring Boot Failure

### ISSUE THREAD

**Issue by alidursen** [swe-ms-boun/2018fall-swe574-g1#77]
For one reason or other, my IDE was failing to import dependencies. After an hour of trial and error on pom.xml we have not identified the cause but at least a problem. Please see this [link](https://stackoverflow.com/a/43203400) where addition of thymeleaf properties fixed the issue. Taner can explain in detail in the comments below (if he understood the problem himself in the first place.)

**Comment by taneresme** [comment]
Actually, I have no idea why we had that particular issue related to thymeleaf. It might be because of something in spring.
