### ISSUE TITLE
Common functionalities for header

### ISSUE THREAD

**Issue by taneresme** [swe-ms-boun/2018fall-swe574-g1#84]
* Development of the functions for the requests to retrieve the details to be displayed on ``header`` of the pages accessible by the registered users.
* the response will be containing the information below:
  * Name and surname of the user.
  * ``username`` of the user
  * if any, user profile context.
  * I should be able to call ``/header``

**Comment by alidursen** [comment]
can you explain further?
* who'll call `/header`?
* will this header always be available, or only for logged-in users?

**Comment by taneresme** [comment]
Hi all,

We have done a few changes regarding the requirements below. @alidursen, the information related to the header is providing now for each GET request in the back-end. This functionality implemented for the existing pages (except memory creation).

I am closing this issue if we see a problem or missing, we will create another issue...
