### ISSUE TITLE
Can the system allow non-standard HTML objects?

### ISSUE THREAD

**Issue by tugcanolgun** [swe-ms-boun/2018fall-swe574-g1#91]
Currently any objects that doesn't have closing `/` (slash) gives an error on the system.

Ex:
`<br />` is okay.
`<br>` gives an error. 

Problem occurs because of QuillJS. It produces HTML objects as non-compliant to W3C. In browser, there is no difference between `<br>` and `<br />` but former is not a compliant usage. We need to find a way to disable this check in our system. Is that possible?

**Comment by alidursen** [comment]
According to [W3C documnetation](http://w3c.github.io/html-reference/syntax.html#void-element) `<br />` is acceptable. It says that `/` in the is end "optional" (**Start tags**, item 5)

**Comment by alidursen** [comment]
any updates?

**Comment by taneresme** [comment]
Any update on this topic?

**Comment by tugcanolgun** [comment]
Closing the issue. Customizing quilljs for our needs sorted the issue.
