### ISSUE TITLE
Military service todos

### ISSUE THREAD

**Issue by macukadam** [swe-ms-boun/2018fall-swe574-g1#95]
Hello all, as all of you know our national army needs me at the front line. I will be on duty between 26 November -17 December so you can sleep comfortably at night. 

Anyways I won't be here for three weeks so I won't be able to join weekly meetings unfortunately. I had a branch named "feature/macukadam/CreationOfEntites" it can be deleted because @vedatakses allready merged related entities into the develop branch and this branch became obsolote. 

Besides that I wrote a wiki page about possible annotation libraries for front end development.  It seems libraries are compatible with our memory creation style. It will be a piece of cake for @tugcanolgun and @taneresme.  And also I did a little research about "Storing Annotation To Opensource Free Annotation Services".  I don't know if it's too late or not but it is wise to check them before going too deep with annotation server stuff. @alidursen maybe you can harness some good features of them.

I will close this issue when I turn back.

🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷🇹🇷
<pre>                                 ŞAFAK 21</pre>
🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷🇹🇷

**Comment by taneresme** [comment]
@macukadam is this issue still valid :)

**Comment by macukadam** [comment]
Nope. It's over. I am back. :)
